version: "3.8"
services:
  backend:
    build: ./backend
    container_name: mean-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/cruddb

  frontend:
    build: ./frontend
    container_name: mean-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mean-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
