version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: suhelkhan12/backend:latest
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb+srv://workwithsuhel:erOMdtcMcn3BmHjS@application.wxs32.mongodb.net/app
    depends_on:
      - mongo

  frontend:
    image: suhelkhan12/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo-data:


