name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mean-backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/mean-backend

      - name: Build and push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mean-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/mean-frontend

      - name: Deploy on VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/crud-dd-task-mean-app
            git pull origin main
            docker-compose pull
            docker-compose up -d
